---
title: "Monte Carlo Simulation"
author: "R. Noah Padgett"
date: "2020-10-22"
output: html_document
---

```{r setup, echo=F, warning=F, error=F, message=F}

library(xtable)
library(tidyr)
library(dplyr)
library(ggplot2)
library(simsem)

library(coda)
library(mvtnorm)
library(lavaan)
library(data.table)
library(tcltk)

# Set Seed for Reproducibility
set.seed(20201113)

# summary objects
nrep <- 1000
nvar <- 2
sim.res <- as.data.frame(matrix(nrow=nrep, ncol=nvar))

```


# Proposed Model with Analytic Expectations

```{r}

lambda <- matrix(
  c(rep(0.8,4), rep(0,4), rep(0,4),
    rep(0,4), rep(0.8,4), rep(0,4),
    rep(0,4), rep(0,4), rep(0.8,4)), 
  ncol=3
)
phi <- matrix(
  c(1, 0.3, 0.1,
    0.3, 1, 0.2,
    0.1, 0.2, 1),
  ncol=3
)
psi <- diag(1, ncol=12, nrow=12)
psi[2, 3] <- psi[3, 2] <- 0.25
psi[4, 7] <- psi[7, 4] <- 0.3

sigma <- lambda%*%phi%*%t(lambda) + psi

sigma

psi_m <- diag(1, ncol=12, nrow=12)

sigma_m <- lambda%*%phi%*%t(lambda) + psi_m

sigma_m - sigma

```


# Simulation Study


```{r sim-dist, warning=F, error=F, message=F}

# specify population model
population.model <- ' 
  f1 =~ 0.8*y1 + 0.8*y2 + 0.8*y3 + 0.8*y4
  f2 =~ 0.8*y5 + 0.8*y6 + 0.8*y7 + 0.8*y8
  f3 =~ 0.8*y9 + 0.8*y10 + 0.8*y11 + 0.8*y12
  
  # Factor (co)variances
  f1 ~~ 1*f1 + 0.3*f2 + 0.1*f3
  f2 ~~ 1*f2 + 0.2*f3
  f3 ~~ 1*f3
  # residual covariances
  y2 ~~ 0.1*y3
  y4 ~~ 0.3*y7
'



# analysis model
analysis.model1 <- ' 
  f1 =~ NA*y1 + y2 + y3 + y4
  f2 =~ NA*y5 + y6 + y7 + y8 
  f3 =~ NA*y9 + y10 + y11 + y12 
  
  # Factor covariances
  f1 ~~ 1*f1 + f2 + f3
  f2 ~~ 1*f2 + f3
  f3 ~~ 1*f3
  
  # residual covariances
  y2 ~~ y3
  y4 ~~ y7
'


Output <- sim(nrep, model=analysis.model1,silent = T,
              n=500, generate=population.model,
              lavaanfun = "cfa")

sim.res[,1:2] <- Output@stdCoef[, c("y2~~y3", "y4~~y7")]


colnames(sim.res) <- c("y2~~y3", "y4~~y7")
plot_dat <- sim.res %>%
  pivot_longer(
    cols=everything(),
    names_to = "Parameter",
    values_to = "Estimate"
  ) %>%
  mutate(V = ifelse(Parameter %like% "=~", 0.30, 0.25))

p <- ggplot(plot_dat, aes(x=Estimate))+
  geom_density(adjust = 2)+
  geom_vline(aes(xintercept = V), linetype="dashed")+
  #geom_vline(aes(xintercept = -V), linetype="dashed")+
  facet_wrap(.~Parameter)+
  theme_bw()
p

mean(sim.res[,1] > 0.25)
mean(sim.res[,2] > 0.25)

```


# Laplace Approximation

```{r run-lppa, warning=F, error=F, message=F}



wd <- getwd()
source(paste0(wd, "/code/utility_functions.R"))
source(paste0(wd, "/code/laplace_functions.R"))


# specify population model
population.model <- ' 
  f1 =~ 0.8*y1 + 0.8*y2 + 0.8*y3 + 0.8*y4
  f2 =~ 0.8*y5 + 0.8*y6 + 0.8*y7 + 0.8*y8
  f3 =~ 0.8*y9 + 0.8*y10 + 0.8*y11 + 0.8*y12
  
  # Factor (co)variances
  f1 ~~ 1*f1 + 0.3*f2 + 0.1*f3
  f2 ~~ 1*f2 + 0.2*f3
  f3 ~~ 1*f3
  # residual covariances
  y4 ~~ 0.3*y7
  y2 ~~ 0.1*y3
'

# generate data
myData <- simulateData(population.model, sample.nobs=500L)

# fit model
myModel <- ' 
  f1 =~ y1 + y2 + y3 + y4
  f2 =~ y5 + y6 + y7 + y8 
  f3 =~ y9 + y10 + y11 + y12 
  
  # Factor covariances
  f1 ~~ f2 + f3
  f2 ~~ f3

'
fit <- cfa(myModel, data=myData)
summary(fit, standardized=T)

lfit <- laplace_local_fit(
  fit, data=myData, cut.load = 0.30, cut.cov = 0.25,
  standardize = T, pb = F,
  opt=list(scale.cov=1, no.samples=10000))

library(kableExtra)

kable(lfit$Summary, format="html", digits=3) %>%
  kable_styling(full_width = T) %>%
  scroll_box(width="100%", height = "500px")

```



## Sampling Distributions


```{r}

# transform
plot_dat_laplace <- lfit$`All Results` %>%
  pivot_longer(
    cols=everything(),
    names_to = "Parameter",
    values_to = "Estimate"
  )

plot_dat_laplace <- filter(plot_dat_laplace,
                           Parameter %in% c("y3~~y2", "y7~~y4")) %>%
  mutate(V = ifelse(Parameter %like% "=~", 0.30, 0.25),
         Parameter = ifelse(Parameter == "y3~~y2",
                            "cov(y[2], y[3])", "cov(y[4], y[7])"))


plot_dat_emp <- sim.res %>%
  pivot_longer(
    cols=everything(),
    names_to = "Parameter",
    values_to = "Estimate"
  ) %>%
  mutate(V = ifelse(Parameter %like% "=~", 0.30, 0.25),
         Parameter = ifelse(Parameter == "y2~~y3",
                            "cov(y[2], y[3])", "cov(y[4], y[7])"))

lty <- c("True" = 1, "Laplace" = 2)

p <- ggplot()+
  geom_density(data=plot_dat_emp, adjust = 2,
               aes(x=Estimate, linetype="True"))+
  geom_density(data=plot_dat_laplace, adjust = 2,
               aes(x=Estimate, linetype="Laplace"))+
  #geom_vline(xintercept = 0.25, linetype="dotted")+
  scale_linetype_manual(values = lty, name=NULL)+
  facet_wrap(.~Parameter, labeller = label_parsed)+
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.background = element_blank(),
        legend.position = "bottom",
        text=element_text(size=13))
p

ggsave("manuscript/fig/sampling_dist.pdf", p, units="in", width=7, height=3.5)


```